services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    # web と同一ネットワーク名前空間を共有するため、こちらで 80 を公開
    ports:
      - "80:80"

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    # nginx.conf は 127.0.0.1:9000 を参照するため、php のネットワークを共有
    network_mode: "service:php"
    depends_on:
      - php

  db:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: