name Test
on:
  pull_request:
    paths: ['*.php']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-php@v2
        with:
          php-version: '7.2'
      - run: vendor/bin/phpunit --configuration phpunit.xml
